apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ name }}-rq
spec:
  hard:
    requests.cpu: "{{ cpu_request | default('2') }}"
    requests.memory: {{ memory_request | default('4Gi') }}
    limits.cpu: "{{ cpu_limit | default('4') }}"
    limits.memory: {{ memory_limit | default('8Gi') }}
